default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pai
  password: tigers
  host: db

development:
  <<: *default
  database: paiapp_dev

test:
  <<: *default
  database: paiapp_test

production:
  <<: *default
  database: paiapp_production
  username: paiapp
  password: <%= ENV["PAIAPP_DATABASE_PASSWORD"] %>
